/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLGV_netbeans;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.GiangVien;
import model.GiangVienDAO;

/**
 *
 * @author ACER
 */
public class NewJFrame extends javax.swing.JFrame {
    SimpleDateFormat date_format = new SimpleDateFormat("dd/MM/yyyy");
    GiangVienDAO dao = new GiangVienDAO();
    String strHinhAnh = "";

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public void fillDateTABLE() {
        DefaultTableModel model = (DefaultTableModel)tbGiangVien.getModel();
        model.setRowCount(0);
        for (GiangVien gv : dao.getAllGiangVien()) {
            Object rowData[] = new Object[7];
            rowData[0] = gv.getMaGV();
            rowData[1] = gv.getTenGV();
            rowData[2] = date_format.format(gv.getNgaySinh());
            rowData[3] = gv.isGioiTinh()?"NAM":"NU";
            rowData[4] = gv.getEmail();
            rowData[5] = gv.getDiaChi();
            rowData[6] = gv.getHinhAnh();
            model.addRow(rowData);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTenGV = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaGV = new javax.swing.JTextField();
        txtTenGV = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        lblHinhAnh = new javax.swing.JLabel();
        btnLuu = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGiangVien = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(59, 89, 152));

        jPanel1.setBackground(new java.awt.Color(59, 89, 152));
        jPanel1.setAlignmentX(2.0F);
        jPanel1.setAlignmentY(2.0F);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\rsz_1logo_hau.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 148, 222));
        jLabel2.setText(" ĐẠI HỌC KIẾN TRÚC HÀ NỘI");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("HANOI ARCHITECHTURAL UNIVERSITY");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CHƯƠNG TRÌNH QUẢN LÝ GIẢNG VIÊN HAU");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MÃ GV:");

        lblTenGV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenGV.setForeground(new java.awt.Color(255, 255, 255));
        lblTenGV.setText("HỌ VÀ TÊN:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NGÀY SINH:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EMAIL:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("GIỚI TÍNH:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ĐỊA CHỈ:");

        txtMaGV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGVActionPerformed(evt);
            }
        });

        txtNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaySinhActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdNam);
        rdNam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdNam.setSelected(true);
        rdNam.setText("NAM");

        buttonGroup1.add(rdNu);
        rdNu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rdNu.setText("NỮ");
        rdNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNuActionPerformed(evt);
            }
        });

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane1.setViewportView(txtDiaChi);

        jLabel12.setText("HINH ANH");

        lblHinhAnh.setText("HÌNH ẢNH");
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblHinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhAnhMouseClicked(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Desktop\\img\\save.png")); // NOI18N
        btnLuu.setText("LƯU");
        btnLuu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnThem.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Desktop\\img\\add.png")); // NOI18N
        btnThem.setText("THÊM");
        btnThem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Desktop\\img\\edit.png")); // NOI18N
        btnSua.setText("SỬA");
        btnSua.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Desktop\\img\\delete.png")); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        tbGiangVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbGiangVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã GV", "Tên GV", "Ngày Sinh", "Giới Tính", "Email", "Địa Chỉ", "Hình Ảnh"
            }
        ));
        tbGiangVien.setVerifyInputWhenFocusTarget(false);
        tbGiangVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGiangVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbGiangVien);
        if (tbGiangVien.getColumnModel().getColumnCount() > 0) {
            tbGiangVien.getColumnModel().getColumn(0).setHeaderValue("Mã GV");
            tbGiangVien.getColumnModel().getColumn(1).setHeaderValue("Tên GV");
            tbGiangVien.getColumnModel().getColumn(2).setHeaderValue("Ngày Sinh");
            tbGiangVien.getColumnModel().getColumn(3).setHeaderValue("Giới Tính");
            tbGiangVien.getColumnModel().getColumn(4).setHeaderValue("Email");
            tbGiangVien.getColumnModel().getColumn(5).setHeaderValue("Địa Chỉ");
            tbGiangVien.getColumnModel().getColumn(6).setHeaderValue("Hình Ảnh");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel4))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(43, 43, 43)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdNam)
                                .addGap(18, 18, 18)
                                .addComponent(rdNu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenGV))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaGV, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtTenGV)
                            .addComponent(txtNgaySinh)
                            .addComponent(txtEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(595, 595, 595)))
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenGV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenGV))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(rdNam)
                                    .addComponent(rdNu))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = tbGiangVien.getSelectedRow();

    // Kiểm tra xem có dòng nào được chọn không
            if (selectedRowIndex == -1) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một giảng viên để xóa.");
                return; // Nếu không có dòng nào được chọn, thoát khỏi hàm
            }

            // Xác nhận việc xóa thông tin giảng viên
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa thông tin giảng viên này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                // Xóa dòng được chọn từ bảng
                DefaultTableModel model = (DefaultTableModel) tbGiangVien.getModel();
                model.removeRow(selectedRowIndex);

                // Hiển thị thông báo hoặc thực hiện các hành động khác sau khi xóa thành công
                JOptionPane.showMessageDialog(this, "Đã xóa thông tin giảng viên.");
            }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tbGiangVien.getSelectedRow();

    // Kiểm tra xem người dùng đã chọn dòng nào trong bảng chưa
        if (selectedRowIndex == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một giảng viên để sửa thông tin.");
            return; // Nếu không có dòng nào được chọn, thoát khỏi hàm
        }

        // Lấy thông tin từ các trường dữ liệu trên giao diện
        String maGV = txtMaGV.getText();
        String tenGV = txtTenGV.getText();
        String ngaySinh = txtNgaySinh.getText();
        String gioiTinh = rdNam.isSelected() ? "NAM" : "NU";
        String email = txtEmail.getText();
        String diaChi = txtDiaChi.getText();

        // Lấy model từ bảng
        DefaultTableModel model = (DefaultTableModel) tbGiangVien.getModel();

        // Cập nhật thông tin giảng viên trong bảng
        model.setValueAt(maGV, selectedRowIndex, 0);
        model.setValueAt(tenGV, selectedRowIndex, 1);
        model.setValueAt(ngaySinh, selectedRowIndex, 2);
        model.setValueAt(gioiTinh, selectedRowIndex, 3);
        model.setValueAt(email, selectedRowIndex, 4);
        model.setValueAt(diaChi, selectedRowIndex, 5);

        // Hiển thị thông báo hoặc thực hiện các hành động khác sau khi sửa thành công
        JOptionPane.showMessageDialog(this, "Thông tin giảng viên đã được cập nhật.");
    }//GEN-LAST:event_btnSuaActionPerformed
    public void reset(){
        txtDiaChi.setText("");
        txtMaGV.setText("");
        txtNgaySinh.setText("");
        txtTenGV.setText("");
        txtEmail.setText("");
        rdNam.isSelected();
        lblHinhAnh.setText("HINH ANH");
        lblHinhAnh.setIcon(null);
        strHinhAnh = null;
    }
    
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        reset();
        
    }//GEN-LAST:event_btnThemActionPerformed
    public boolean validateForm(){
        return !(txtMaGV.getText().isEmpty() || txtTenGV.getText().isEmpty() || txtNgaySinh.getText().isEmpty() || txtEmail.getText().isEmpty() || txtDiaChi.getText().isEmpty() || lblHinhAnh.getIcon() == null);
    }
    public GiangVien getModel() throws ParseException{
        GiangVien gv = new GiangVien();
        gv.setMaGV(txtMaGV.getText());
        gv.setTenGV(txtTenGV.getText());
        gv.setEmail(txtEmail.getText());
        boolean gt = false;
        if(rdNam.isSelected()){
            gt=true;
        }
        gv.setGioiTinh(gt);
        gv.setDiaChi(txtDiaChi.getText());
        gv.setNgaySinh(date_format.parse(txtNgaySinh.getText()));
        if(strHinhAnh == null) {
            gv.setHinhAnh("NO AVATAR");
        }else {
            gv.setHinhAnh(strHinhAnh);
        }
        return gv;
    }
    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        if(validateForm()){
            try {
                GiangVien gv = getModel();
                if (dao.add(gv)>0) {
                    JOptionPane.showMessageDialog(this, "luu thanh cong");
                    fillDateTABLE();
                }
            } catch (ParseException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Ban chua nhap day du thong tin");
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void lblHinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhAnhMouseClicked
         try {
            JFileChooser jfc = new JFileChooser();
            jfc.showOpenDialog(null);
            File file = jfc.getSelectedFile();
        
            if (file != null) {
                Image img = ImageIO.read(file);
                strHinhAnh = file.getName();
                lblHinhAnh.setText("");
            
            // Lấy kích thước hiện tại của JLabel
                int width = lblHinhAnh.getWidth();
                int height = lblHinhAnh.getHeight();
            
                // Scale hình ảnh để hiển thị trong JLabel
                Image scaledImg = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
                lblHinhAnh.setIcon(new ImageIcon(scaledImg));
            } else {
                lblHinhAnh.setText("NO AVATAR");
                lblHinhAnh.setIcon(null);
                strHinhAnh = null;
        }
    } catch (IOException ex) {
             // Xử lý lỗi nếu có

    }
    }//GEN-LAST:event_lblHinhAnhMouseClicked

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaySinhActionPerformed

    private void txtMaGVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGVActionPerformed

    private void rdNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdNuActionPerformed
    public void setModel(){
        int rowIndex = tbGiangVien.getSelectedRow(); // Lấy chỉ số của hàng được chọn
        if (rowIndex >= 0) {
            String maGV = tbGiangVien.getValueAt(rowIndex, 0).toString();
            String tenGV = tbGiangVien.getValueAt(rowIndex, 1).toString();
            String ngaySinh = tbGiangVien.getValueAt(rowIndex, 2).toString();
            String gioiTinh = tbGiangVien.getValueAt(rowIndex, 3).toString();
            String email = tbGiangVien.getValueAt(rowIndex, 4).toString();
            String diaChi = tbGiangVien.getValueAt(rowIndex, 5).toString();
            String hinhAnh = tbGiangVien.getValueAt(rowIndex, 6).toString();
            txtMaGV.setText(maGV);
            txtTenGV.setText(tenGV);
            txtNgaySinh.setText(ngaySinh);
            // Xử lý giới tính
            if (gioiTinh.equalsIgnoreCase("NAM")) {
                rdNam.setSelected(true);
            } else {
                rdNu.setSelected(true);
            }
            txtEmail.setText(email);
            txtDiaChi.setText(diaChi);

            // Placeholder cho txtNgaySinh
            txtNgaySinh.setForeground(Color.GRAY);
            txtNgaySinh.setText("Ngày sinh (dd/mm/yyyy)");
            txtNgaySinh.addFocusListener(new FocusListener() {
                @Override
                public void focusGained(FocusEvent e) {
                    if (txtNgaySinh.getText().equals("Ngày sinh (dd/mm/yyyy)")) {
                        txtNgaySinh.setText("");
                        txtNgaySinh.setForeground(Color.BLACK);
                    }
                }

                @Override
                public void focusLost(FocusEvent e) {
                    if (txtNgaySinh.getText().isEmpty()) {
                        txtNgaySinh.setForeground(Color.GRAY);
                        txtNgaySinh.setText("Ngày sinh (dd/mm/yyyy)");
                    }
                }
            });
        }
        //load hinh anh
            
            
    }
    private void tbGiangVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGiangVienMouseClicked
        // TODO add your handling code here:
         int rowIndex = tbGiangVien.getSelectedRow(); // Lấy chỉ số của hàng được chọn
            if (rowIndex >= 0) {
                String maGV = tbGiangVien.getValueAt(rowIndex, 0).toString();
                String tenGV = tbGiangVien.getValueAt(rowIndex, 1).toString();
                String ngaySinh = tbGiangVien.getValueAt(rowIndex, 2).toString();
                String gioiTinh = tbGiangVien.getValueAt(rowIndex, 3).toString();
                String email = tbGiangVien.getValueAt(rowIndex, 4).toString();
                String diaChi = tbGiangVien.getValueAt(rowIndex, 5).toString();
                String hinhAnh = tbGiangVien.getValueAt(rowIndex, 6).toString();

                txtMaGV.setText(maGV);
                txtTenGV.setText(tenGV);
                txtNgaySinh.setText(ngaySinh);

                // Xử lý giới tính
                if (gioiTinh.equalsIgnoreCase("NAM")) {
                    rdNam.setSelected(true);
                } else {
                    rdNu.setSelected(true);
                }

                txtEmail.setText(email);
                txtDiaChi.setText(diaChi);

                // Load hình ảnh
                if (hinhAnh.equalsIgnoreCase("NO AVATAR")) {
                    lblHinhAnh.setText("NO AVATAR");
                    lblHinhAnh.setIcon(null);
                } else {
                    String imagePath = "C:\\Users\\ACER\\Documents\\img\\" + hinhAnh;

                    try {
                        ImageIcon imgIcon = new ImageIcon(imagePath);
                        Image img = imgIcon.getImage().getScaledInstance(lblHinhAnh.getWidth(), lblHinhAnh.getHeight(), Image.SCALE_SMOOTH);
                        lblHinhAnh.setIcon(new ImageIcon(img));
                        lblHinhAnh.setText(""); // Nếu bạn muốn xóa bất kỳ văn bản nào trên JLabel
                    } catch (Exception ex) {
                        // Xử lý lỗi nếu không tìm thấy hình ảnh
                        lblHinhAnh.setText("Error loading image");
                        lblHinhAnh.setIcon(null);
                    }
                }
                
            }
                
    }//GEN-LAST:event_tbGiangVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblTenGV;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tbGiangVien;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtTenGV;
    // End of variables declaration//GEN-END:variables

    
}
